### ISSUE TITLE
[ask] Samsung galaxy J2 prime

### ISSUE THREAD

**Issue by Zxce3** [Exynos3475/local_manifest#1]
I want to ask, can this be ported to Samsung J2 prime [grandppltedx]
> Actually I want to try to make Ubuntu touch but I can't find a usable kernel

Can u help me?

**Comment by TBM13** [comment]
No, the J2 Prime doesn't have an Exynos 3475 SoC, none of this will work on it

**Comment by Zxce3** [comment]
> No, the J2 Prime doesn't have an Exynos 3475 SoC

do you have any reference about the kernel?

**Comment by TBM13** [comment]
I don't know much about that device, but you should probably try looking at this
https://forum.xda-developers.com/t/rom-g532x-7-1-2-alpha-lineageos-14-1-for-galaxy-j2-prime.3946388/
You can find the link of the kernel source used by that ROM there

**Comment by Zxce3** [comment]
Thanks
